language: java
sudo: required
dist: trusty
group: deprecated-2017Q4

jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)


services:
  - mysql

install: true

before_script:
  - mysql -e 'CREATE DATABASE oms;'

script:
  - mvn -q install --settings settings.xml

notifications:
  email:
  - herve.tchepannou@gmail.com

#deploy:
#  provider: heroku
#  api_key: $HEROKU_API_KEY
#  app: io-tchepannou-omg
#  on: master
