spring:
  datasource:
    jdbcUrl: jdbc:mysql://k.cwj11t2vidmo.us-east-1.rds.amazonaws.com:3306/oms?useSSL=false&requireSSL=false&serverTimezone=UTC
    username: ${database.user}
    password: ${database.password}

swagger:
  protocol: https
