server:
  port: 18083

enigma:
  assetUrl: "http://localhost:28080"
  service:
    ferari:
      port: 18081
      booking:
        url: "http://localhost:${enigma.service.ferari.port}/v1/bookings"
      product:
        url: "http://localhost:${enigma.service.ferari.port}/v1/products"
    refdata:
      port: 18080
      city:
        url: "http://localhost:${enigma.service.refdata.port}/v1/cities"
      site:
        url: "http://localhost:${enigma.service.refdata.port}/v1/sites"
    profile:
      port: 18084
      merchant:
        url: "http://localhost:${enigma.service.profile.port}/v1/merchants"
    finance:
      port: 18085
      order:
        url: "http://localhost:${enigma.service.finance.port}/v1/orders"
