server:
  port: 18083

enigma:
  assetUrl: "http://localhost:28080"
  service:
    ferari:
      port: 18081
      booking:
        url: "http://localhost:${enigma.service.ferari.port}/v1/bookings"
      product:
        url: "http://localhost:${enigma.service.ferari.port}/v1/products"
