spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/oms?useSSL=false&requireSSL=false&serverTimezone=UTC
    username: root
    #password:
    connectionTimeout: 30000
    connectionTestQuery: "SELECT 1"
    maximumPoolSize: 5
    idleTimeout: 600000             # 10 mins
    maxLifetime: 1800000            # 30 mins
    leakDetectionThreshold: 0       # Never
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: enigma.voyage.dev@gmail.com
    password: enigma123
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

swagger:
  version: "1.0"
  title: Order Management API
  description: Order Management API
  termsPath: ""
  email: "herve.tchepannou@gmail.com"
  licenceType: ""
  licencePath: "#"
  protocol: http
  path: "/v1/.*?"

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  security:
    enabled: false

endpoints:
  enabled: true
  health:
    sensitive: false
  metrics:
    enabled: true

logging:
  level:
    root: INFO
    io.tchepannou.core.rest: WARN
    com.amazonaws: ERROR
    org.springframework: INFO
    org.hibernate: ERROR
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF
    springfox: ERROR

  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"

enigma:
  assetUrl: "https://io-tchepannou-enigma-ui.herokuapp.com"
  service:
    email:
      from: "enigma.voyage.dev@gmail.com"
    expirer:
      cron: "0 0/15 * * * ?"
    order:
      orderTTLMinutes: 10
    ferari:
      url: "https://io-tchepannou-ferari.herokuapp.com"
    refdata:
      city:
        url: "https://io-tchepannou-ref-data.herokuapp.com/v1/cities"
      site:
        url: "https://io-tchepannou-ref-data.herokuapp.com/v1/sites"
    profile:
      merchant:
        url: "https://io-tchepannou-profile.herokuapp.com/v1/merchants"
