server:
  port: 18083

enigma:
  assetUrl: "http://localhost:28080"
  service:
    ferari:
      url: "http://localhost:18081"
    tontine:
      url: "http://localhost:18082"
    refdata:
      port: 18080
      city:
        url: "http://localhost:${enigma.service.refdata.port}/v1/cities"
      site:
        url: "http://localhost:${enigma.service.refdata.port}/v1/sites"
    profile:
      port: 18084
      merchant:
        url: "http://localhost:${enigma.service.profile.port}/v1/merchants"
