ALTER TABLE T_ORDER ADD COLUMN mobile_number VARCHAR(15);

ALTER TABLE T_TICKET ADD COLUMN origin_id INTEGER NOT NULL;
ALTER TABLE T_TICKET ADD COLUMN destination_id INTEGER NOT NULL;
ALTER TABLE T_TICKET ADD COLUMN product_id INTEGER NOT NULL;
ALTER TABLE T_TICKET ADD COLUMN merchant_id INTEGER NOT NULL;
ALTER TABLE T_TICKET ADD COLUMN departure_datetime DATETIME NOT NULL;
