ALTER TABLE T_ORDER ADD COLUMN creation_datetime DATETIME;
ALTER TABLE T_ORDER ADD COLUMN checkout_datetime DATETIME;
ALTER TABLE T_ORDER ADD COLUMN cancellation_datetime DATETIME;
ALTER TABLE T_ORDER ADD COLUMN mobile_provider VARCHAR(20);

ALTER TABLE T_TRANSACTION DROP COLUMN cancellation_fk;

DROP TABLE T_CANCELLATION;
